In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
from requests_html import HTMLSession
s = HTMLSession()

In [2]:
df = pd.read_csv('carsSemiProcessed.csv')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3486 entries, 0 to 3485
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car type           3486 non-null   object
 1   car name           3486 non-null   object
 2   year               3473 non-null   float64
 3   url                3486 non-null   object
 4   Pros               3486 non-null   object
 5   Cons               3486 non-null   object
 6   Full Description   3486 non-null   object
 7   rating             3054 non-null   object
 8   current price Min  3075 non-null   object
 9   current price Max  3075 non-null   object
 10  base msrp          3433 non-null   object
 11  engine             3429 non-null   object
 12  drivetrain         3479 non-null   object
 13  dimensions         3471 non-null   object
dtypes: float64(1), object(13)
memory usage: 381.4+ KB

In [10]:
df.describe(include='all')

,car type,car name,year,url,Pros,Cons,Full Description,rating,current price Min,current price Max,base msrp,engine,drivetrain,dimensions
count,3486,3486,3473.000000,3486,3486,3486,3486,3054,3075,3075,3433,3429,3479,3471
unique,19,285,NaN,3486,2428,2501,3377,28,2293,1965,2091,947,73,2348
top,toyota,honda civic,NaN,https://www.edmunds.com/jeep/wrangler/1998/rev...,empty,empty,No changes.,4.5 out of 5 stars,Not Available,"$22,990",N/A \n,"V8 cylinder \n Horsepower: 355 hp @ 5,600 rpm ...",Type: front wheel drive \n Transmission: 5-spe...,Length: 224.1 in. / Height: 81.6 in. \n Overal...
freq,393,37,NaN,1,239,239,10,315,22,24,448,32,288,13
mean,NaN,NaN,2011.823783,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,30.675367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1500.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,2006.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,2014.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,3500.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#df[df['car name'].str.contains('honda civic')]

In [4]:
df = pd.read_csv('cars_brands_description.csv')

In [5]:
df.head()

,Unnamed: 0.1,Unnamed: 0,url,Pros,Cons,Full Description
0,0,0,https://www.edmunds.com/jeep/wrangler/1998/rev...,"['Unmatched off-road capability, overflowing w...","['Soft top is fun, but still a pain in the $%!...",Jeep has improved off-road capability by incre...
1,1,1,https://www.edmunds.com/lexus/is-350/2014/review/,"['Powerful and refined V6', 'superbly crafted ...","[""Handling isn't very sharp, even with the F S...","For 2014, the Lexus IS 350 is redesigned. High..."
2,2,2,https://www.edmunds.com/toyota/4runner/2005/re...,"['Powerful engine lineup, well mannered on pav...","[""Cargo capacity isn't much more than what man...",The base V6 now comes with a five-speed automa...
3,3,3,https://www.edmunds.com/toyota/tundra/2002/rev...,"['Silky V8, Toyota build quality, less-than-fu...",['Lacks wide range of choice offered by domest...,"SR5 models have new 16-inch wheels, and a limi..."
4,4,4,https://www.edmunds.com/acura/rdx/2017/review/,['Strong acceleration and fuel economy from st...,['Technology interface can be distracting to u...,The Acura RDX essentially carries over unchang...

In [6]:
df["car type"] = df["url"].str.split('/').str[3]
df['car name'] = df['url'].str.split('/').str[3] + ' ' + df['url'].str.split('/').str[4]
df['year'] = df['url'].str.split('/').str[5]

In [7]:
#remove the first 2 columns
df = df.drop(df.columns[[0, 1]], axis=1)

In [8]:
#reorder the columns
df = df[['car type', 'car name', 'year', 'url', 'Pros', 'Cons','Full Description']]

In [9]:
#count each unique value in year column
df['year'].value_counts()

        278
2021    222
2020    215
2019    193
2018    179
2017    165
2016    152
2015    148
2014    132
2013    127
2012    115
2011    113
2010    112
2009    104
2008    104
2007     94
2023     91
2006     83
2005     79
2004     74
2003     73
2002     72
2001     72
2000     61
1999     54
1998     49
1997     48
1996     43
1995     41
2022     36
1994     34
1993     34
1992     29
1991     29
1990     27
2024      4
Name: year, dtype: int64

In [10]:
#count nan values
df['year'].isnull().sum()

278

In [10]:
# if value in year is '' make it NaN
df['year'] = df['year'].replace('', np.nan)

In [11]:
df['year1']=df["Full Description"].str.extract("(\d{4})")
df['year'] = df['year'].fillna(df['year1'])
df=df.drop(['year1'],axis=1)

In [12]:
df

,car type,car name,year,url,Pros,Cons,Full Description
0,jeep,jeep wrangler,1998,https://www.edmunds.com/jeep/wrangler/1998/rev...,"['Unmatched off-road capability, overflowing w...","['Soft top is fun, but still a pain in the $%!...",Jeep has improved off-road capability by incre...
1,lexus,lexus is-350,2014,https://www.edmunds.com/lexus/is-350/2014/review/,"['Powerful and refined V6', 'superbly crafted ...","[""Handling isn't very sharp, even with the F S...","For 2014, the Lexus IS 350 is redesigned. High..."
2,toyota,toyota 4runner,2005,https://www.edmunds.com/toyota/4runner/2005/re...,"['Powerful engine lineup, well mannered on pav...","[""Cargo capacity isn't much more than what man...",The base V6 now comes with a five-speed automa...
3,toyota,toyota tundra,2002,https://www.edmunds.com/toyota/tundra/2002/rev...,"['Silky V8, Toyota build quality, less-than-fu...",['Lacks wide range of choice offered by domest...,"SR5 models have new 16-inch wheels, and a limi..."
4,acura,acura rdx,2017,https://www.edmunds.com/acura/rdx/2017/review/,['Strong acceleration and fuel economy from st...,['Technology interface can be distracting to u...,The Acura RDX essentially carries over unchang...
...,...,...,...,...,...,...,...
3481,lexus,lexus rx-450hl,2022,https://www.edmunds.com/lexus/rx-450hl/,['Impeccable cabin finished with top-quality m...,['Third-row space is tight for anyone other th...,Combining fuel efficiency with seven-passenge...
3482,toyota,toyota mirai,2023,https://www.edmunds.com/toyota/mirai/,['Longer driving range than many battery elect...,"['Hydrogen stations are few and far between', ...",People looking for alternatives to gas-powere...
3483,chevrolet,chevrolet traverse,2018,https://www.edmunds.com/chevrolet/traverse/,"['Generous passenger room in all three rows', ...",['Rear seats and thick roof pillars significan...,"These days, vehicles need to exceed expectati..."
3484,bmw,bmw 4-series,2023,https://www.edmunds.com/bmw/4-series/2023/m440i/,"['Powerful and fuel-efficient engines', ""Sport...",['Flat hood makes it hard to place the front e...,The 4 Series is based on the 3 Series sedan b...
3485,ford,ford f-250-super-duty,2022,https://www.edmunds.com/ford/f-250-super-duty/...,['Diesel V8 generates immense power and torque...,"['Price tag soars with options', 'Tall ride he...","If Ford knows how to do anything, it's build ..."

In [21]:
s = HTMLSession()
def get_website(url):
    response = s.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    return soup

def get_rating(soup):
    rating = soup.find('span', class_='average-user-rating')
    if rating is None:
        return None
    return rating.text

def get_princing(soup):
    princigDiv = soup.find('div', class_='intro-trims-content')
    if princigDiv is None:
        return None, None
    pricing = princigDiv.find('td', class_='text-right align-top')
    if pricing is None:
        return None, None
    li = pricing.text.split('-')
    if len(li) == 1:
        return li[0], li[0]
    return li[0], li[1]

def get_car_features(soup):
    features = soup.find('div', class_='features-lists')
    if features is None:
        return None
    return features.text

def get_car_specs(soup):
    specs = soup.find('div', class_='features-specs')
    #print("specs", specs)
    if specs is None:
        return None, None, None, None
    dl = specs.find_all('dl')
    #print("dl", dl)
    if dl is None:
        return None, None, None, None
    # iterate through each dl and check df text if it exists extract all dd text from dl
    base_msrp = ''
    engine = ''
    Drivetrain = ''
    Dimenstions = ''
    for ele in dl:
        if ele.dt.text == 'Base MSRP' or ele.dt.text == 'Total MSRP':
            # get list of dd elements from ele
            base_msrpList = ele.find_all('dd')
            #ieterate through each dd element and get text
            for ele1 in base_msrpList:
                base_msrp += ele1.text + ' \n '
        if ele.dt.text == 'Engine':
            engineList = ele.find_all('dd')
            for ele1 in engineList:
                engine += ele1.text + ' \n '
        if ele.dt.text == 'Drivetrain':
            DrivetrainList = ele.find_all('dd')
            for ele1 in DrivetrainList:
                Drivetrain += ele1.text + ' \n '
        if ele.dt.text == 'Dimensions':
            DimenstionsList = ele.find_all('dd')
            for ele1 in DimenstionsList:
                Dimenstions += ele1.text + ' \n '

    return base_msrp, engine, Drivetrain, Dimenstions

In [14]:
#check element number 3076 of df
df.iloc[3076]['url']

'https://www.edmunds.com/bmw/m5-cs/'

In [17]:
soup = get_website(df.iloc[3076]['url'])
rating = get_rating(soup)
priceMin, priceMax = get_princing(soup)
get_car_specs(soup)

('$143,995 \n ',
 'V8 cylinder \n Horsepower: 627 hp @ 6,000 rpm \n Torque: 553 lb-ft @ 1,800 rpm \n ',
 'Type: all wheel drive \n Transmission: 8-speed shiftable automatic \n ',
 'Length: 196.4 in. / Height: 57.8 in. \n Overall Width with Mirrors: 83.7 in. \n Overall Width without Mirrors: 74.9 in. \n Curb Weight: 4,114 lbs. \n Cargo Capacity, All Seats In Place: 14.0 cu.ft. \n ')

In [45]:
print(get_car_specs(soup))

('', 'V8 cylinder \n Horsepower: 627 hp @ 6,000 rpm \n Torque: 553 lb-ft @ 1,800 rpm \n ', 'Type: all wheel drive \n Transmission: 8-speed shiftable automatic \n ', 'Length: 196.4 in. / Height: 57.8 in. \n Overall Width with Mirrors: 83.7 in. \n Overall Width without Mirrors: 74.9 in. \n Curb Weight: 4,114 lbs. \n Cargo Capacity, All Seats In Place: 14.0 cu.ft. \n ')

In [25]:
# test get_car_specs on 10 rows
# imprt sleep and random
from time import sleep
import random
for i in range(10):
    url = df['url'][i]
    #sleep(random.uniform(0, 1))
    soup = get_website(url)
    print(get_car_specs(soup))

('N/A \n ', 'Inline 4 cylinder \n Horsepower: 120 hp @ 5,400 rpm \n Torque: 140 lb-ft @ 3,500 rpm \n ', 'Type: four wheel drive \n Transmission: 5-speed manual \n ', 'Length: 147.7 in. / Height: 69.6 in. \n Overall Width without Mirrors: 66.7 in. \n Curb Weight: 3,045 lbs. \n Cargo Capacity, All Seats In Place: 11.1 cu.ft. \n ')
('$39,615 \n ', 'V6 cylinder \n Horsepower: 306 hp @ 6,400 rpm \n Torque: 277 lb-ft @ 4,800 rpm \n ', 'Type: rear wheel drive \n Transmission: 8-speed shiftable automatic \n ', 'Length: 183.7 in. / Height: 56.3 in. \n Overall Width without Mirrors: 71.3 in. \n Curb Weight: 3,593 lbs. \n Cargo Capacity, All Seats In Place: 13.8 cu.ft. \n ')
('$27,795 \n ', 'V6 cylinder \n Horsepower: 245 hp @ 5,200 rpm \n Torque: 282 lb-ft @ 3,800 rpm \n ', 'Type: rear wheel drive \n Transmission: 5-speed automatic \n ', 'Length: 189.0 in. / Height: 68.5 in. \n Overall Width without Mirrors: 73.8 in. \n Curb Weight: 4,045 lbs. \n Cargo Capacity, All Seats In Place: 36.6 cu.ft. \n ')
('$15,605 \n ', 'V6 cylinder \n Horsepower: 190 hp @ 4,800 rpm \n Torque: 220 lb-ft @ 3,600 rpm \n Base Engine Size: 3.4 L \n Base Engine Type: Gas \n ', 'Type: rear wheel drive \n Transmission: 5-speed manual \n ', "Length: 217.5 in. / Height: 70.5 in. \n Bed Length: 8'2” \n Overall Width without Mirrors: 75.2 in. \n Curb Weight: 3,795 lbs. \n ")
('$35,670 \n ', 'V6 cylinder \n Horsepower: 279 hp @ 6,200 rpm \n Torque: 252 lb-ft @ 4,900 rpm \n ', 'Type: front wheel drive \n Transmission: 6-speed shiftable automatic \n ', 'Length: 184.4 in. / Height: 65.0 in. \n Overall Width without Mirrors: 73.7 in. \n Curb Weight: 3,737 lbs. \n Cargo Capacity, All Seats In Place: 26.1 cu.ft. \n ')
('$30,970 \n ', 'V8 cylinder \n Horsepower: 310 hp @ 5,200 rpm \n Torque: 334 lb-ft @ 4,500 rpm \n ', 'Type: rear wheel drive \n Transmission: 4-speed automatic \n ', 'Length: 224.1 in. / Height: 82.1 in. \n Overall Width without Mirrors: 79.2 in. \n Curb Weight: 5,644 lbs. \n Cargo Capacity, All Seats In Place: 92.1 cu.ft. \n ')
('$69,900 \n ', 'Inline 6 cylinder \n Horsepower: 473 hp @ 6,250 rpm \n Torque: 442 lb-ft @ 2,600 rpm \n ', 'Type: all wheel drive \n Transmission: 8-speed shiftable automatic \n ', 'Length: 186.2 in. / Height: 65.6 in. \n Overall Width with Mirrors: 84.2 in. \n Overall Width without Mirrors: 74.7 in. \n Curb Weight: 4,620 lbs. \n Cargo Capacity, All Seats In Place: 28.7 cu.ft. \n ')
('$25,735 \n ', 'V6 cylinder \n Horsepower: 265 hp @ 6,250 rpm \n Torque: 250 lb-ft @ 4,500 rpm \n ', 'Type: front wheel drive \n Transmission: 6-speed automatic \n ', 'Length: 185.7 in. / Height: 67.0 in. \n Overall Width without Mirrors: 75.8 in. \n Curb Weight: 4,078 lbs. \n Cargo Capacity, All Seats In Place: 32.1 cu.ft. \n ')
('$24,985 \n ', 'V6 cylinder \n Horsepower: 195 hp @ 4,600 rpm \n Torque: 260 lb-ft @ 2,800 rpm \n ', 'Type: rear wheel drive \n Transmission: 4-speed automatic \n ', 'Length: 224.1 in. / Height: 83.7 in. \n Overall Width without Mirrors: 79.2 in. \n Curb Weight: 4,919 lbs. \n Cargo Capacity, All Seats In Place: 270.4 cu.ft. \n ')
('$34,600 \n ', 'Inline 6 cylinder \n Horsepower: 230 hp @ 6,500 rpm \n Torque: 200 lb-ft @ 2,750 rpm \n ', 'Type: rear wheel drive \n Transmission: 6-speed manual \n ', 'Length: 178.2 in. / Height: 55.9 in. \n Overall Width without Mirrors: 71.5 in. \n Curb Weight: 3,362 lbs. \n Cargo Capacity, All Seats In Place: 12.0 cu.ft. \n ')

In [26]:
#iterate over url column
from tqdm import tqdm
for index, row in tqdm(df.iterrows()):
    url = row['url']
    #sleep(random.uniform(0, 1))
    soup = get_website(url)
    rating = get_rating(soup)
    priceMin, priceMax = get_princing(soup)
    base_msrp, engine, Drivetrain, Dimensions = get_car_specs(soup)
    #print((base_msrp, engine, Drivetrain, Dimensions))
    df.at[index, 'rating'] = rating
    df.at[index, 'current price Min'] = priceMin
    df.at[index, 'current price Max'] = priceMax
    df.at[index, 'base msrp'] = base_msrp
    df.at[index, 'engine'] = engine
    df.at[index, 'drivetrain'] = Drivetrain
    df.at[index, 'dimensions'] = Dimensions

3486it [1:03:45,  1.10s/it]

In [27]:
#save to csv
df.to_csv('carsSemiProcessed.csv', index=False)

In [29]:
#check if there are any null values
df.isnull().sum()

car type               0
car name               0
year                  13
url                    0
Pros                   0
Cons                   0
Full Description       0
rating               432
current price Min    411
current price Max    411
base msrp              7
engine                 7
drivetrain             7
dimensions             7
dtype: int64

3486

In [32]:
df

,car type,car name,year,url,Pros,Cons,Full Description,rating,current price Min,current price Max,base msrp,engine,drivetrain,dimensions
0,jeep,jeep wrangler,1998,https://www.edmunds.com/jeep/wrangler/1998/rev...,"['Unmatched off-road capability, overflowing w...","['Soft top is fun, but still a pain in the $%!...",Jeep has improved off-road capability by incre...,4.3 out of 5 stars,"$2,423","$4,074",N/A \n,"Inline 4 cylinder \n Horsepower: 120 hp @ 5,40...",Type: four wheel drive \n Transmission: 5-spee...,Length: 147.7 in. / Height: 69.6 in. \n Overal...
1,lexus,lexus is-350,2014,https://www.edmunds.com/lexus/is-350/2014/review/,"['Powerful and refined V6', 'superbly crafted ...","[""Handling isn't very sharp, even with the F S...","For 2014, the Lexus IS 350 is redesigned. High...",4.6 out of 5 stars,"$23,990","$27,990","$39,615 \n","V6 cylinder \n Horsepower: 306 hp @ 6,400 rpm ...",Type: rear wheel drive \n Transmission: 8-spee...,Length: 183.7 in. / Height: 56.3 in. \n Overal...
2,toyota,toyota 4runner,2005,https://www.edmunds.com/toyota/4runner/2005/re...,"['Powerful engine lineup, well mannered on pav...","[""Cargo capacity isn't much more than what man...",The base V6 now comes with a five-speed automa...,4.8 out of 5 stars,"$4,364","$6,983","$27,795 \n","V6 cylinder \n Horsepower: 245 hp @ 5,200 rpm ...",Type: rear wheel drive \n Transmission: 5-spee...,Length: 189.0 in. / Height: 68.5 in. \n Overal...
3,toyota,toyota tundra,2002,https://www.edmunds.com/toyota/tundra/2002/rev...,"['Silky V8, Toyota build quality, less-than-fu...",['Lacks wide range of choice offered by domest...,"SR5 models have new 16-inch wheels, and a limi...",4.7 out of 5 stars,"$3,324","$5,612","$15,605 \n","V6 cylinder \n Horsepower: 190 hp @ 4,800 rpm ...",Type: rear wheel drive \n Transmission: 5-spee...,Length: 217.5 in. / Height: 70.5 in. \n Bed Le...
4,acura,acura rdx,2017,https://www.edmunds.com/acura/rdx/2017/review/,['Strong acceleration and fuel economy from st...,['Technology interface can be distracting to u...,The Acura RDX essentially carries over unchang...,4.3 out of 5 stars,"$19,982","$29,990","$35,670 \n","V6 cylinder \n Horsepower: 279 hp @ 6,200 rpm ...",Type: front wheel drive \n Transmission: 6-spe...,Length: 184.4 in. / Height: 65.0 in. \n Overal...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3481,lexus,lexus rx-450hl,2022,https://www.edmunds.com/lexus/rx-450hl/,['Impeccable cabin finished with top-quality m...,['Third-row space is tight for anyone other th...,Combining fuel efficiency with seven-passenge...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3482,toyota,toyota mirai,2023,https://www.edmunds.com/toyota/mirai/,['Longer driving range than many battery elect...,"['Hydrogen stations are few and far between', ...",People looking for alternatives to gas-powere...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3483,chevrolet,chevrolet traverse,2018,https://www.edmunds.com/chevrolet/traverse/,"['Generous passenger room in all three rows', ...",['Rear seats and thick roof pillars significan...,"These days, vehicles need to exceed expectati...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3484,bmw,bmw 4-series,2023,https://www.edmunds.com/bmw/4-series/2023/m440i/,"['Powerful and fuel-efficient engines', ""Sport...",['Flat hood makes it hard to place the front e...,The 4 Series is based on the 3 Series sedan b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3485,ford,ford f-250-super-duty,2022,https://www.edmunds.com/ford/f-250-super-duty/...,['Diesel V8 generates immense power and torque...,"['Price tag soars with options', 'Tall ride he...","If Ford knows how to do anything, it's build ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df['Full Description'][0]

"Jeep has improved off-road capability by increasing the axle ratio offered with the 4.0-liter engine and revising the torsion bar for better steering. Optional this year on the 1998 Jeep Wrangler are a tilting driver seat, automatic speed control, a combination CD/cassette stereo, a new Smart Key Immobilizer theft-deterrent system and two new colors. We were a little concerned last year when we heard that Jeep was giving its bad-boy mud-machine  an overhaul. Luckily, the Wrangler hasn't received the leather interior, cellular phone makeover that has recently emasculated so much of the sport-utility segment. No, the Wrangler remains the drive-me-hard-through-the-slop beast of yesterday, with a few appreciated improvements.Jeep Wranglers have long been the standard for those valiant explorers who truly wish to go where no one has gone before. The go-anywhere ability of the Wrangler has been improved by the Quadra-coil suspension which allows an additional seven inches of articulation over the old leaf spring set-up; thus resulting in increased approach and departure angles. Jeep boasts that the Quadra-coil suspension, as well as improved shocks and tires, also greatly improves the Wrangler's on-road manners.The Wrangler receives minor adjustments to the powertrain by combining the Dana 44 rear axle with a 3.73 axle ratio, replacing the 3.55 axle ratio with the 4.0-liter engine.  And Jeep claims that a revised torsion bar provides improved steering response.  Nobody, however, will mistake this vehicle for a smooth-running family sedan; the Wrangler is very much a truck. A five-speed manual transmission remains standard and a three-speed automatic is available for those who don't plan on doing any serious off-roading.For 1998, most people will not notice any changes to the Wrangler other than the new Chili Pepper Red and Deep Amethyst exterior colors.  Front bumper guards have been added and a new underhood lamp will aid in finding the wiper fluid reservoir in the dark.  A TLEV (Transitional Low Emission Vehicle) 4.0-liter inline six-cylinder engine is available for states adopting California emission regulations, so Jeep owners  can feel even closer to nature: they make less smog.Over the past two years, Jeep has done a great job improving the Wrangler. Gone are some of the nagging complaints we had about safety, wind noise and engine roar; what remains is a solid truck with hard-core capabilities and rugged good looks. This is obviously not the truck for everybody, but those willing to put up with a cloth interior and a little road noise will be rewarded with an amazingly fun vehicle. Hey, they even brought back those snazzy round headlights ... what's not to like?"